# Generated by Django 4.0.3 on 2022-10-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesrecord_automobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='id',
            new_name='employee_id',
        ),
    ]
