# Generated by Django 4.0.3 on 2022-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_id_salesperson_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialcustomer',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialcustomer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
